#Check Player Arena Addon for MBedwars by dejwideek

#Permissions
permissions:
  check: "bw.checkplayerarena.check"
  reload: "bw.checkplayerarena.reload"

#Messages
#RGB colors are supported. (1.16+ only)
messages:
  usage: "&cUsage: /checkarena <player>"
  not-found: "&cThis player isn't online!"
  no-inside-arena: "&cThis player isn't playing!"

  #Available placeholder: %permission%
  no-permission: "&cYou must have permission &4%permission% &cto do this!"

  #Available placeholders: %player%, %arena%
  arena-info: "&6%player% &eis playing on &c%arena%"

  reloaded: "&eSuccessfully reloaded configuration file!"